### ISSUE TITLE
Small screens should collapse header to fit application title

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/patterns#27]
At the moment, viewing it on a small screen shows multiple lines for the logo / name of the app, taking up a lot of real estate. 
![screen shot 2015-04-07 at 15 30 01](https://cloud.githubusercontent.com/assets/761444/7031636/fe5ef040-dd3a-11e4-834e-5e184dc68148.png)

What if the logo hid the "City of Philadelphia" and just showed the liberty bell so that the name of the application could fit? The liberty bell is probably tall enough to fit two lines of application name.

This is probably a pattern portfolio question rather than a property question so I'll post it here

**Comment by timwis** [comment]
lol sry about the giant screenshot. The world isn't ready for my retina screen!

**Comment by kdemi** [comment]
My concern with hiding the text on mobile is that it's the only indication that you are on a phila.gov website (besides the address bar). Is the bell alone strong enough branding? @majshehab @kyleodum

**Comment by kyleodum** [comment]
@timwis @kdemi For purpose of developing a successful brand we need the bell and the words "city of philadelphia" to help define the new alpha site.  Since this site is living on alpha, we need to wait till traffic grows before we tweak the logo.  Once the "Bell" is fully recognizable as part of the logo on the new site, the "City of Philadelphia" text (think the Pepsi circle) can be removed

**Comment by majshehab** [comment]
if the concern is the initial loading/mobile screen real estate, removing the breadcrumb and divider would help.  

Wouldn't shrink or edit the logo or the disclaimer for all of the reasons mentioned above.

**Comment by timwis** [comment]
Okee doke
